DROP TABLE IF EXISTS area_nivel;
DROP TABLE IF EXISTS area;
DROP TABLE IF EXISTS nivel_curso;
DROP TABLE IF EXISTS nivel;
DROP TABLE IF EXISTS aula_edificio;
DROP TABLE IF EXISTS aula;
DROP TABLE IF EXISTS espacio;
DROP TABLE IF EXISTS edificio;
DROP TABLE IF EXISTS curso_paralelo;
DROP TABLE IF EXISTS paralelo;  
DROP TABLE IF EXISTS curso;
DROP TABLE IF EXISTS persona_idioma;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS personal;
DROP TABLE IF EXISTS colegio;


DROP TABLE IF EXISTS rol_privilegio;
DROP TABLE IF EXISTS privilegio;

DROP TABLE IF EXISTS rol;
DROP TABLE IF EXISTS idioma;
DROP TABLE IF EXISTS financiamiento;
DROP TABLE IF EXISTS formacion;
DROP TABLE IF EXISTS funcion;


DROP TYPE IF EXISTS estado_enum;
DROP TYPE IF EXISTS genero_enum;
DROP TYPE IF EXISTS estado_enum_b;



